### ISSUE TITLE
Replace `runningSince` field  type of server status to timestamp

### ISSUE THREAD

**Issue by Kalovelo** [aeternity/state-channel-demo#158]
It would be much clearier to use a timestamp instead of a date string for the service status object.

see: https://github.com/aeternity/state-channel-demo/blob/develop/server/src/services/bot/bot.interface.ts#L32

**Comment by ArshErgon** [comment]
I have started a pull request here https://github.com/aeternity/state-channel-demo/pull/160

**Comment by Kalovelo** [comment]
Thank you @ArshErgon !
