### ISSUE TITLE
readme & tutorial: include diagram that shows communication

### ISSUE THREAD

**Issue by marc0olo** [aeternity/state-channel-demo#244]
client (browser) <-> node <-> node <-> server (bot)

@velzevur you just showed me a nice diagram on slack. I think we should add this here in the README as well as in the intro of the tutorial.

what do you think? @smaroudasunicorn @Kalovelo @martinkaintas @omar-saadoun

**Comment by marc0olo** [comment]
something like this but specifically showing the parts of the demo. for the node communication we could say that the demo uses only 1 node instance but typically you'd have different nodes communicating with each other encrypted via enoise.

![image (4)](https://user-images.githubusercontent.com/8124114/201874686-89803977-e785-4b60-95ac-c64cf845a6f2.png)

**Comment by Kalovelo** [comment]
closing this as it is now included
