### ISSUE TITLE
pre-push hook undocumented and broken?

### ISSUE THREAD

**Issue by marc0olo** [aeternity/state-channel-demo#96]
wanted to push changes in regards to devmode rollback crash fix and I am unable to push the branch:

```sh
FAIL  src/utils/sdk-service/sdk-service.test.ts > SDK > integration > creates game channel instance, initializes Channel and returns coins to faucet on channel closing
FetchError: request to http://localhost:3000/open failed, reason: connect ECONNREFUSED 127.0.0.1:3000
 ❯ ClientRequest.<anonymous> node_modules/node-fetch/lib/index.js:1491:11
 ❯ ClientRequest.emit node:events:527:28
 ❯ Socket.socketErrorListener node:_http_client:454:9
 ❯ Socket.emit node:events:527:28

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed | 8 passed (9)
     Tests  1 failed | 39 passed (40)
      Time  10.75s (in thread 9.94s, 108.15%)

husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'git@github.com:aeternity/state-channel-demo.git'
```

can somebody enlighten me about the requirements? the local setup is actually started with `docker-compose up -d` in case this is required

**Comment by Kalovelo** [comment]
Contract project is more or less separated from client and server apps - they use different docker configurations, therefore the pre-push hooks depend on running `docker-compose up` at the project root level and not in contract folder level. 

We will need to merge those options in order to depend on a single docker configuration

**Comment by marc0olo** [comment]
@Kalovelo I ran the `docker-compose up` at project root level. the tests are broken for me. cannot push

**Comment by Kalovelo** [comment]
Client tests depend on server as well, therefore before pushing: `cd server && npm run dev`.

We will probably need to document this on contributing :smile:

**Comment by marc0olo** [comment]
> We will probably need to document this on contributing 😄

100% :-)

I wasn't aware about any hook at all and got a little bit surprised.

**Comment by Kalovelo** [comment]
We could, but the test pipeline was introduced here later than expected so husky was quite useful at the time. Also I was thinking that using our own resources than waiting for the github pipeline could be more optimal

**Comment by marc0olo** [comment]
but we run the github pipeline for tests anyway, right? 🤔 

my personal opinion:
- pre-commit linting-check: yes
- pre-push hook: no

**Comment by Kalovelo** [comment]
Noted! #98
